// 用户验证表
CREATE TABLE auths(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(10) NOT NULL,
password VARCHAR(10) NOT NULL,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

// 新人信息表
CREATE TABLE users(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
he_name VARCHAR(10) NOT NULL,
she_name VARCHAR(10) NOT NULL,
wedding_date VARCHAR(10) NOT NULL,
wedding_lunar VARCHAR(10) NOT NULL,
share_msg VARCHAR(255) NOT NULL,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

// 酒店信息表
CREATE TABLE hotels(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
hotel_name VARCHAR(50) NOT NULL,
hotel_address VARCHAR(50) NOT NULL,
hotel_lat FLOAT(10) NOT NULL,
hotel_lng FLOAT(10) NOT NULL,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
user_id BIGINT(20)
)
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

// 祝福评论表
CREATE TABLE comments(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
bless_msg TEXT,
nick_name TEXT,
wx_face TEXT,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
user_id BIGINT(20)
)
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
